backend:
  name: git-gateway
  branch: main

media_folder: "client/public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menu"
    folder: "client/src/content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Category Name", name: "category", widget: "string"}
      - {label: "Category Name (Japanese)", name: "categoryJa", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 0}
      - label: "Items"
        name: "items"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Price", name: "price", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
